version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: expense_tracker
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  spring-app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: spring_app_container
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/expense_tracker
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      LOGGING_FILE_NAME: /logs/app.log
      LOGGING_FILE_PATH: /logs
      LOGGING_LEVEL_ROOT: INFO
    depends_on:
      - postgres
    volumes:
      - app-logs:/logs
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
  app-logs:
    external: true