FROM php:8.2-apache

# Copy your local website files into the container
COPY ./jee_lab/ /var/www/html/

# Enable mod_rewrite if needed
RUN a2enmod rewrite

# Set working directory
WORKDIR /var/www/html/